#!/usr/bin/env python

import numpy as np
from matplotlib import pyplot as plt
import sys

stride = 20 # set me yo

print 'Loading: %s' % sys.argv[-1]
spots = np.genfromtxt(sys.argv[-1])
real_deltas = []
recip_deltas = []
q_mags = []

for i in range(0, spots.shape[0], stride):
    for j in range(i+1, spots.shape[0], stride):
        v1 = spots[i,:3]
        v2 = spots[j,:3]
        q1 = spots[i,3:6]
        q2 = spots[j,3:6]
        real_deltas.append( np.linalg.norm(v1 - v2) )
        recip_deltas.append( np.linalg.norm(q1 - q2) )
        q_mags.append( np.linalg.norm(q1) )

print 'measured %d distances' % len(real_deltas)

plt.figure(figsize=(15,5))

ax1 = plt.subplot(131)
ax1.set_title('Distance Between Spots')
ax1.hist(real_deltas, bins=np.arange(0.0,250,0.1), histtype='step')
ax1.set_xlim([0, 250])
ax1.set_xlabel('pixels')
ax1.set_ylabel('frequency')

ax2 = plt.subplot(132)
ax2.hist(q_mags, bins=np.linspace(0.0, 10.0, 500), histtype='step')
ax2.set_xlim([0, 5.0])
ax2.set_xlabel('$q \ \AA^{-1}$')
ax2.set_ylabel('frequency')

ax3 = plt.subplot(133)
ax3.set_title('Recip Lattice Vectors')
ax3.hist(recip_deltas, bins=np.linspace(0.0, 10.0, 500), histtype='step')
ax3.set_xlim([0, 5.0])
ax3.set_xlabel('$q \ \AA^{-1}$')
ax3.set_ylabel('frequency')

plt.show()

